### ISSUE TITLE
gradients calculation in Eq. 5

### ISSUE THREAD

**Issue by Liumouliu** [vislearn/ngdsac_camreloc#1]
Hi, Thank you for this great paper.

May I ask how the gradient (d(log(p(H_k,w)))/dw) in Eq. 5 are calculated?

I found the following code to calcuate it:

	// gradients of (log) neural guidance arise from an indicator tensor
	// where we mark which minimal sets have been sampled
	for(unsigned h = 0; h < initHyps.size(); h++)
	for(int j = 0; j < 4; j++)
	{
		int x = sampledPoints[h][j].x;
		int y = sampledPoints[h][j].y;

		neuralGuidanceGrads[0][0][y][x] += 1;
	}

I think it is absolutely correct. But I'm confused by how the gradient (d(log(p(H_k,w)))/dw) is transformed into an indicator function.  

1) Count the selected minimal sets can be the gradients? Where is the log() function? It seems for me the counting operations results in a posterior distribution p(w|H_k).

2) The variable neuralGuidanceGrads is not normalized (sum to 1), however, the input neuralGuidance is normalized (sum to 1). 

If we do not normalize the variable neuralGuidanceGrads and since it depends on the number of initHyps, does this mean that sampling more initHyps can generate larger gradients of neuralGuidance?

Thank you very much!

liu

**Comment by ebrach** [comment]
Hi liu,

sorry for the late response but I was travelling. Regarding your questions:

1. For numerical stability, the network predicts log probabilities and we calculate the gradients of the log probabilities which turns into an indicator function.  In Eq. 5 we would not derive wrt. to parameters _w_ but wrt. _log p( . |w)_.

https://github.com/vislearn/ngdsac_camreloc/blob/723b4820e106f4d222302a7640306963de5f2a63/train_e2e.py#L98-L100

Note how we back propagate via `log_ng`  instead of `neural_guidance`.

https://github.com/vislearn/ngdsac_camreloc/blob/723b4820e106f4d222302a7640306963de5f2a63/train_e2e.py#L165

2. The normalization is hidden in the network architecture which means we let PyTorch autograd take care of this.

https://github.com/vislearn/ngdsac_camreloc/blob/723b4820e106f4d222302a7640306963de5f2a63/network.py#L102-L110

Hope that helps!
Eric

**Comment by csyhy1986** [comment]
> Hi, Thank you for this great paper.
> 
> May I ask how the gradient (d(log(p(H_k,w)))/dw) in Eq. 5 are calculated?
> 
> I found the following code to calcuate it:
> 
> ```
> // gradients of (log) neural guidance arise from an indicator tensor
> // where we mark which minimal sets have been sampled
> for(unsigned h = 0; h < initHyps.size(); h++)
> for(int j = 0; j < 4; j++)
> {
> 	int x = sampledPoints[h][j].x;
> 	int y = sampledPoints[h][j].y;
> 
> 	neuralGuidanceGrads[0][0][y][x] += 1;
> }
> ```
> 
> I think it is absolutely correct. But I'm confused by how the gradient (d(log(p(H_k,w)))/dw) is transformed into an indicator function.
> 
> 1. Count the selected minimal sets can be the gradients? Where is the log() function? It seems for me the counting operations results in a posterior distribution p(w|H_k).
> 2. The variable neuralGuidanceGrads is not normalized (sum to 1), however, the input neuralGuidance is normalized (sum to 1).
> 
> If we do not normalize the variable neuralGuidanceGrads and since it depends on the number of initHyps, does this mean that sampling more initHyps can generate larger gradients of neuralGuidance?
> 
> Thank you very much!
> 
> liu

hi, pls refer to https://github.com/vislearn/ngransac/issues/14
